### ISSUE TITLE
Initial setup questions

### ISSUE THREAD

**Issue by jerwarren** [gpavlidi/slangouts#1]
I've put in auth tokens for both services, and it displays output that suggests i'ts able to talk to both.

But any time I send a message to either service, slangouts says:

2016/03/10 03:26:45 Slack: Got msg from a group ( C0PBEL3G8 ) not cached locally. Refreshing groups.  
2016/03/10 03:26:45 Slack: Cant find group C0PBEL3G8 even after updating Groups. Skipping message: test

This implies that it's somehow not able to update groups.  Can you tell me what I'm missing?

**Comment by jerwarren** [comment]
Oh, I figured out what's going on.  slangouts creates the slack channel for each conversation only when a message comes in on it.  I was sending messages in hangouts expecting them to sync over to slack.

**Comment by gpavlidi** [comment]
Thats right @jerwarren , i should probably make that clearer in the readme.
